name = "Hugo LaosPR"
license = "MIT"
licenselink = "https://github.com/laospr/hugo-laospr/blob/master/LICENSE.md"
description = "The LaosPR Theme for www.laospr.net"
homepage = "https://laospr.net/"
tags = ["blog","responsive","personal","google analytics","portfolio","disqus","bootstrap","font awesome","projects","creative","landing page","product","white","share this"]
features = ["blog","responsive","personal","google analytics","portfolio","disqus","bootstrap","font awesome","projects","creative","landing page","product","white","share this"]
min_version = "0.1"

[author]
  name = "Nakhonekham Xongmixay"
  homepage = "https://laospr.net/lohn"

[original]
  name = "Hugo-Initio"
  author = "Miguel Simoni"
  homepage = "https://miguelsimoni.xyz/hugo-initio-site/"
  repo = "https://github.com/miguelsimoni/hugo-initio/"
